POST http://localhost:3000/users.json
Content-Type: application/json

{
"first_name": "luke",
"last_name": "nilsson",
"email": "bro@example.com",
"password": "password",
"password_confirmation": "password"
}